<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EConnectMvcApp.Domain\EConnectMvcApp.Domain.csproj" />
    <!--<ProjectReference Include="..\EConnectMvcApp.Infrastructure\EConnectMvcApp.Infrastructure.csproj" /> -->
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
