<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
      <ProjectReference Include="..\EConnectMvcApp.Application\EConnectMvcApp.Application.csproj" />
	  <ProjectReference Include="..\EConnectMvcApp.Infrastructure\EConnectMvcApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>

</Project>
